name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    env:
      SHARDS_OPTS: --ignore-crystal-version
    steps:
      - name: Download source
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          shards: nightly

      - name: Install SDL2
        if: runner.os == 'Linux'
        run: sudo apt-get -y install libsdl2-dev
      - name: Install SDL2
        if: runner.os == 'macOS'
        run: brew install sdl2
      - name: Install SDL2
        if: runner.os == 'Windows'
        run: |
          iwr https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip -OutFile sdl2.zip
          7z x sdl2.zip
          mv SDL2-* sdl2
          echo "INCLUDE=$(pwd)\sdl2\include:${env:INCLUDE}" >>${env:GITHUB_ENV}
          echo "LIB=$(pwd)\sdl2\lib\x64:${env:LIB}" >>${env:GITHUB_ENV}

      - name: Install shards
        run: shards install --skip-postinstall
      - name: Build extensions
        working-directory: lib/imgui-backends
        run: make
      - name: Build
        run: shards build
      # - name: Run tests
      #   run: crystal spec

      - name: Gather files
        if: runner.os == 'Linux'
        run: |
          mkdir dist
          cp --dereference bin/crab lib/imgui-backends/cimgui/libcimgui.so dist/
      - name: Gather files
        if: runner.os == 'Windows'
        run: |
          mkdir dist
          cp bin/crab.exe lib/x64/SDL2.dll lib/imgui-backends/cimgui/cimgui.dll dist/
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Crab${{runner.os}}
          path: dist
